### ISSUE TITLE
Changing your webpages's title

### ISSUE THREAD

**Issue by lopes-andre** [kurtispykes/kurtispykes.github.io#1]
Hello Kurtis,

Very nice job. The only thing I'd change is the title of your portfolio webpage's. Apparently you are still using the stantard title that came with the boilerplate template.

In order to do that, go to the `<head></head>` section and edit the text inside the `<title></title>` tags. You will find "Prologue by HTML5 UP" and you may change with the title you find fits you the most.

I hope it was useful.

Cheers!

**Comment by kurtispykes** [comment]
Thank you. This has been solved!
